### ISSUE TITLE
Fix Online or App?

### ISSUE THREAD

**Issue by trafort** [Mountio/Mintio#1]

**Comment by radioblahaj** [comment]
I'm gonna Asign Mech to this 
@amazinigmech2418

**Comment by AmazingMech2418** [comment]
Online and can be an app.

**Comment by radioblahaj** [comment]
We can phonegap to build html,css and js to convert to android

**Comment by radioblahaj** [comment]
Thanks @trafort

**Comment by AmazingMech2418** [comment]
You are correct @redmangospros .

**Comment by radioblahaj** [comment]
Thanks.

**Comment by AmazingMech2418** [comment]
You're welcome!

**Comment by radioblahaj** [comment]
So, What needs to be doen here mech?

**Comment by radioblahaj** [comment]
https://www.quora.com/topic/Mountio

**Comment by AmazingMech2418** [comment]
WOW! You got a topic on Mountio!

**Comment by radioblahaj** [comment]
i made it
